from metronome import metronome
from time import sleep

metro = metronome()
metro.set_serial("COM3")
metro.set_bpm(120)
metro.play()
sleep(3)
metro.pause()
sleep(1)
print("resume")
metro.unpause(120, 1200)
sleep(3)
metro.pause()
metro.strum("down")
sleep(1)
metro.strum("down")
sleep(1)
metro.strum("down")
sleep(1)
sleep(2)
metro.strum("up")
sleep(1)
metro.strum("up")
sleep(1)
metro.strum("up")
sleep(1)
metro.play()
sleep(2)
metro.pause()